# Generated by Django 4.0.3 on 2022-03-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='birouri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locuri_totale_birouri', models.PositiveIntegerField(blank=True, null=True)),
                ('etaj_birouri', models.PositiveIntegerField(blank=True, null=True)),
                ('hardware_birouri', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='cereri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_cerere', models.CharField(max_length=150)),
                ('motiv_cerere', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='cladiri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tara_cladire', models.CharField(max_length=100)),
                ('judet_cladire', models.CharField(max_length=100)),
                ('oras_cladire', models.CharField(max_length=100)),
                ('strada_cladire', models.CharField(max_length=100)),
                ('cod_postal_cladire', models.CharField(max_length=100)),
                ('nr_birouri_cladire', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
