# Generated by Django 4.0.3 on 2022-03-13 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0002_birouri_cereri_cladiri'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('varsta', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F'), ('O', 'O')], default='M', max_length=1)),
                ('data_nasterii', models.DateTimeField(default=django.utils.timezone.now)),
                ('nationalitate', models.CharField(max_length=45)),
                ('adresa', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='angajati',
        ),
    ]
