# Generated by Django 4.0.3 on 2022-03-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_profile_delete_angajati'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_country', models.CharField(max_length=100)),
                ('building_county', models.CharField(max_length=100)),
                ('building_city', models.CharField(max_length=100)),
                ('building_street', models.CharField(max_length=100)),
                ('building_zip_code', models.CharField(max_length=100)),
                ('building_offices', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_free_spots', models.PositiveIntegerField(blank=True, null=True)),
                ('office_floor', models.PositiveIntegerField(blank=True, null=True)),
                ('office_hardware', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='cereri',
            new_name='Work_request',
        ),
        migrations.DeleteModel(
            name='birouri',
        ),
        migrations.DeleteModel(
            name='cladiri',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='adresa',
            new_name='profile_address',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='varsta',
            new_name='profile_age',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='data_nasterii',
            new_name='profile_birth_date',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='gender',
            new_name='profile_gender',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='nationalitate',
            new_name='profile_nationality',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='profile_user',
        ),
        migrations.RenameField(
            model_name='work_request',
            old_name='motiv_cerere',
            new_name='work_request_reason',
        ),
        migrations.RenameField(
            model_name='work_request',
            old_name='tip_cerere',
            new_name='work_request_type',
        ),
    ]
