# Generated by Django 4.0.3 on 2022-03-13 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_building_office_rename_cereri_work_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='office_building',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.building'),
        ),
    ]
