# Generated by Django 4.0.3 on 2022-03-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_office_office_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_request',
            name='work_request_type',
            field=models.CharField(choices=[('Remote', 'Remote'), ('Onsite', 'Onsite'), ('Change_office', 'Change_office')], default='Onsite', max_length=14),
        ),
    ]
