# Generated by Django 4.0.3 on 2022-03-14 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_alter_work_request_work_request_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_request',
            name='work_request_building',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.building'),
        ),
        migrations.AddField(
            model_name='work_request',
            name='work_request_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
