# Generated by Django 4.0.3 on 2022-03-14 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_work_request_work_request_building_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_office_located',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.office'),
        ),
        migrations.AlterField(
            model_name='work_request',
            name='work_request_building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.building'),
        ),
        migrations.AlterField(
            model_name='work_request',
            name='work_request_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
