# Generated by Django 4.0.3 on 2022-03-14 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_profile_profile_office_located_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_office_located',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.office'),
        ),
    ]
