# Generated by Django 4.0.3 on 2022-03-14 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_profile_profile_office_located'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='building_floors',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
