# Generated by Django 4.0.3 on 2022-03-14 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_building_building_floors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='office',
            old_name='office_free_spots',
            new_name='office_free_desks',
        ),
        migrations.AddField(
            model_name='office',
            name='office_total_desks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
