# Generated by Django 4.0.3 on 2022-03-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_office_free_spots_office_office_free_desks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='building_name',
            field=models.CharField(default='building', max_length=200),
        ),
        migrations.AddField(
            model_name='office',
            name='office_name',
            field=models.CharField(default='office', max_length=200),
        ),
    ]
